Fix golangci-lint issues
% golangci-lint run ./...
client_test.go:533:2: SA4006: this value of `rpt` is never used (staticcheck)
        rpt, err := client.GetRequestingPartyToken(token.AccessToken, cfg.GoCloak.Realm, RequestingPartyTokenOptions{
        ^
client.go:1517:26: error strings should not be capitalized or end with punctuation or a newline (golint)
                return nil, errors.New("Type of a policy required")
                                       ^
client.go:1593:26: error strings should not be capitalized or end with punctuation or a newline (golint)
                return nil, errors.New("Type of a permission required")